# Generated by Django 3.1.5 on 2021-01-29 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('plan', 'Планируется'), ('act', 'Активная'), ('cont', 'Контроль'), ('fin', 'Завершена')], max_length=4)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('celery', models.CharField(blank=True, max_length=255)),
                ('doer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doer', to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(blank=True, related_name='watchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_status', models.CharField(choices=[('plan', 'Планируется'), ('act', 'Активная'), ('cont', 'Контроль'), ('fin', 'Завершена')], max_length=4)),
                ('curr_status', models.CharField(choices=[('plan', 'Планируется'), ('act', 'Активная'), ('cont', 'Контроль'), ('fin', 'Завершена')], max_length=4)),
                ('changer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_task', to='tracker.task')),
            ],
            options={
                'verbose_name': 'Изменение статуса задачи',
                'verbose_name_plural': 'Изменения статуса задач',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_task', to='tracker.task')),
                ('watchers', models.ManyToManyField(related_name='notification_watchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_id', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.task')),
            ],
            options={
                'verbose_name': 'Задача Celery',
                'verbose_name_plural': 'Задачи Celery',
                'ordering': ['-id'],
            },
        ),
    ]
